name: Workflows
on:
  push:
    branches:
     - labdevsecops

#--------------------- SAST -------------------------------------------

jobs:
  SAST:
    runs-on: windows-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2




#    - name: Validando existencia en de proyecto en SonarCloud
#      id: validateProjectOnSonar
#      run: |
#        set +e
#        curl -f -X POST -u '${{ secrets.SONARCLOUD_TOKEN }}' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'curso-devsecops-rd' -d 'visibility=public'
#        if [ $? -ne 0 ]
#        then 
#          echo "Proyecto existe en SonarCloud"
#        else
#          echo "Proyecto ${{ github.event.repository.name }} fue creado correctamente en SonarCloud"

#          echo "Se establece rama main como rama por defecto"
#          curl -X POST -u '${{ secrets.SONARCLOUD_TOKEN }}:' 'https://sonarcloud.io/api/projects_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
#       fi

    - name: Enable exacution gradlew
      run: |
        chmod 777 gradlew

    - name: Ejecucion SonarQube 
      run: |
        ./gradlew sonarqube \
        -Dsonar.projectKey=${{ github.event.repository.name }}' \
        -Dsonar.organization=curso-devsecops-rd \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} \
        -Dsonar.branch.name=labdevsecops



#--------------------- SCA -------------------------------------------
      
  SCA:
    needs: SAST
    runs-on: windows-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2      

    - name: Build
      id: build
      run: |
        #pwd
        #ls -R
        if [ -f "build.gradle" ]
        then
          echo "Utiliza build.gradle"
          echo "Se habilita permiso sobre archivo gradlew"
          chmod 777 gradlew
          ./gradlew build
        else
          echo "Otro tipo de proyecto"
        fi
    
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Upload Test result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports